name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [content-updated]
  schedule:
    # 每天早上8点自动检查更新（北京时间，UTC+8，所以是UTC 0点）
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For actions/checkout
      pages: write    # For actions/deploy-pages
      id-token: write # For actions/deploy-pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Fetch latest commits
        run: npm run fetch-commits

      - name: Build VitePress site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
